services:
  - type: web
    name: med-doc-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CLAUDE_MODEL
        value: claude-sonnet-4-5-20250929
      - key: USE_CLAUDE
        value: true
      - key: DB_URL
        value: sqlite:///./app.db
      - key: STORAGE_DIR
        value: ./local_storage
      - key: ALLOW_ORIGINS
        value: "*"
